/// Types
interface types {
    /// The error types.
    enum errno {
        runtime-error,
        not-found-error
    }

    /// The cache takes a list of u8s as value
    type payload = list<u8>;
}
